version: 2.1

description: |
    Install and configure the aws command-line Interface (awscli) and push image to ecr

jobs:
    build:
        machine: true
        steps:
            - checkout
            - run:
                name: Install AWS CLI
                command: |
                    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
                    unzip awscliv2.zip
                    sudo ./aws/install
                    aws --version
            - run:
                name: build docker image
                command: |
                    docker build -t fullmotion:$CIRCLE_SHA1 .
                    docker images
            
            - run:
                name: docker login
                command: |
                    aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $aws_account_id.dkr.ecr.us-east-1.amazonaws.com/circlecisluis
            
            - run:
                name: docker tag
                command: |
                    docker tag fullmotion:$CIRCLE_SHA1 $aws_account_id.dkr.ecr.us-east-1.amazonaws.com/circlecisluis:$CIRCLE_SHA1
            
            - run:
                name: docker push
                command: |
                    docker push $aws_account_id.dkr.ecr.us-east-1.amazonaws.com/circlecisluis:$CIRCLE_SHA1
                    
            - run:
                name: Task Definition
                command: |
                    sed -i 's/image/"$aws_account_id.dkr.ecr.us-east-1.amazonaws.com/circlecisluis:$CIRCLE_SHA1"/g' /ecs/task.json
                    cat /ecs/task.json