version: 2.1

description: |
    Install and configure the aws command-line Interface (awscli) and push image to ecr

jobs:
    build:
        machine: true
        steps:
            - run:
                name: Install AWS CLI
                command: |
                    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
                    unzip awscliv2.zip
                    sudo ./aws/install
                    aws --version
            
            - run:
                name: build docker image
                command:
                    docker build -t circleci/fullMotion:$CIRCLE_BRANCH .
                    docker images