version: 2.1

description: |
    Install and configure the aws command-line Interface (awscli) and push image to ecr

jobs:
    build:
        machine: true
        steps:
            - checkout
            - run:
                name: Install AWS CLI
                command: |
                    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
                    unzip awscliv2.zip
                    sudo ./aws/install
            - run:
                name: build docker image
                command: |
                    docker build -t fullmotion:$CIRCLE_SHA1 .
                    docker images
            
            - run:
                name: docker login
                command: |
                    aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $aws_account_id.dkr.ecr.us-east-1.amazonaws.com/circlecisluis
            
            - run:
                name: docker tag
                command: |
                    docker tag fullmotion:$CIRCLE_SHA1 $aws_account_id.dkr.ecr.us-east-1.amazonaws.com/circlecisluis:$CIRCLE_SHA1
            
            - run:
                name: docker push
                command: |
                    docker push $aws_account_id.dkr.ecr.us-east-1.amazonaws.com/circlecisluis:$CIRCLE_SHA1
                    
            - run:
                name: Modify the json
                command: |
                    sed -i 's/AWS_ACCOUNT_ID/'$aws_account_id'/g' ./ecs/task.json
                    sed -i 's/APP_ID/'circlecisluis:$CIRCLE_SHA1'/g' ./ecs/task.json
                
            - run:
                name: Create task Definition
                command: |
                    echo $TERM
                    TASK=$(aws ecs register-task-definition --cli-input-json file://ecs/task.json)
            
            - run:
                name: Update Service
                Command: UPDATE_SERVICE=$(aws ecs update-service --cluster $NAME_CLUSTER --service $NAME_SERVICE --task-definition Full-Motion --desired-count 4)